### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by bepsvpt** [Sunday-Without-God/Judge#1]
- [ ] Store log - 2016/05/10
- [ ] Analysis midterm exam codes - 2016/05/17
- [ ] Improve judge algorithm - 2016/05/24
- [ ] Fix last line which is empty compare bug - 2016/05/24
- [ ] Fix memory limit detect bug - 2016/06/07
- [ ] Intercept system call - 2016/06/14
- [ ] Fix database empty query result will crash judge bug - 2016/06/14
- [ ] Daemonize - 2016/06/28
- [ ] Detect algorithm - 2016/08/31
