### ISSUE TITLE
TODO for Refactor

### ISSUE THREAD

**Issue by DanSnow** [Sunday-Without-God/Judge#2]
- [x] Use ORM for db connection
- [x] Use [docker-py](https://github.com/docker/docker-py)
- [x] Remove commands
- [x] Modulize daemon
- [ ] Move to python3
